### ISSUE TITLE
Issue in converting images to pdf

### ISSUE THREAD

**Issue by vineet-suri** [elwerene/libreoffice-convert#92]
@elwerene While converting image to pdf, the image is rendered on the centre of the page of the converted pdf. Is it possible to adjust top margin of image, relative to the top of the converted pdf document? Not able to find documentation to tweak such options.

A sample converted PDF is below - 
[img.pdf](https://github.com/elwerene/libreoffice-convert/files/10110701/img.pdf)

**Comment by elwerene** [comment]
@vineet-suri  libreoffice-convert is using libreoffice to convert any files. So you need to check if the issue exists with libreoffice. If the issue is with libreoffice, please open a issue on that project. If it works finde in libreoffice, but not in libreoffice-convert, please reopen this issue with more details!
